import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";

import { EdgeStoreProvider } from "@/lib/edgestore";
import "react-day-picker/style.css";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
  viewport: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <EdgeStoreProvider>
        <body className={inter.className}>
          {children}{" "}
          <Toaster
            toastOptions={{
              style: {
                fontSize: "12px",
              },
            }}
          />
        </body>
      </EdgeStoreProvider>
    </html>
  );
}

// suppressHydrationWarning={true}
